---
title: "GEE and GLME"
author: "Jay, Alec, Lynn"
date: "5/27/2021"
output: html_document
---


```{r message = FALSE, warning = FALSE}
library(tidyverse)
library(geepack)
library(nlme)
library(glme)
library(lme4)
```

```{r}
aids = read.csv("aids.csv")


aids = aids %>% 
  mutate(occasion = ceiling(week),
         gender = factor(gender, level = c("male", "female")),
         treatment = as.factor(treatment))


aids = aids %>% 
  mutate(counts = exp(log_cd4) - 1) %>% 
  mutate(counts2 = as.integer(round(counts))) %>% 
  mutate(occasion_sqr = I(occasion^2))


```


log_cd4 ~ occasion + I(occasion^2) + 
             treatment:occasion + treatment:I(occasion^2)
               +  age
               
```{r}
model = glmer(counts2 ~ occasion + I(occasion ^ 2) + treatment:occasion + treatment:I(occasion^2) + age + (1 | id), 
              data = aids,
              family = poisson,
              control = glmerControl(tol = 1e-12),
              nAGQ = 0,
              na.action = na.omit)
summary(model)
```

#Note: Cannot have occasion^2 as a random variable  idk why :(

```{r}
model1 = glmer(counts2 ~ occasion + I(occasion ^ 2) + treatment:occasion + treatment:I(occasion^2) + age + (1 + occasion | id), 
              data = aids,
              family = poisson,
              control = glmerControl(tol = 1e-12),
              nAGQ = 0,
              na.action = na.omit)
summary(model1)
```

Questions: 
Do we need an offset term?
nAGQ is zero is this okay
why cant we add a random effect for quadratic term

The best model that we so far is 

$$log(count) = \beta_0 + \beta1*occasion + \beta2*occasion^2 + \beta3-5 * treatment:occasion + \beta6-8*treatment:occasion^2 $$

